# Generated by Django 3.1.13 on 2021-11-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='group_ptr',
            new_name='group_ptr_id',
        ),
    ]
