# Generated by Django 3.1.13 on 2021-11-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20211102_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='_manager',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
