# Generated by Django 3.1.13 on 2021-11-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_organization__manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_manager',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
