# Generated by Django 3.1.13 on 2021-11-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_project__manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='org_name',
            new_name='_org',
        ),
    ]
