# Generated by Django 3.1.13 on 2021-11-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=151)),
                ('expenseDate', models.DateField()),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('organization', models.CharField(max_length=151)),
                ('project', models.CharField(max_length=151)),
                ('isApproved', models.CharField(default='Pending', max_length=50)),
                ('miles', models.DecimalField(decimal_places=1, default=None, max_digits=8, null=True)),
                ('mileageRate', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('mileageTotal', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('expensePhoto', models.FileField(default=None, null=True, upload_to='')),
                ('expenseCost', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('shipping', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('expenseTotal', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('hours', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('hourlyRate', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('hourTotal', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
            ],
        ),
    ]
