# Generated by Django 3.2.9 on 2021-11-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_auto_20211117_2207'),
        ('Expenses', '0002_auto_20211118_1825'),
        ('Expenses', '0002_auto_20211119_1459'),
    ]

    operations = [
    ]
